#pragma once

#define MAX_QUESTION 256
#define MAX_ANS 100

typedef struct
{
    char question[ MAX_QUESTION ];
    char ansA[ MAX_ANS ];
    char ansB[ MAX_ANS ];
    char ansC[ MAX_ANS ];
    char ansD[ MAX_ANS ];
    char correct;

} Question;

const Question easy[] =
{
    {"How many neighbors does Poland have?", "5", "6", "7", "8", 'C'},
    {"Who was the president of the USA during most of WWII?", "Franklin D. Roosevelt", "Harry S. Truman", "Winston Churchill", "Herbert Hoover", 'A'},
    {"Who won the Ballon d'Or in 2018?", "Cristiano Ronaldo", "Lionel Messi", "Luka Modric", "Michael Jordan", 'C'},
    {"What does the noble motto 'nihil novi' mean in Latin?", "I do not allow", "nothing about us without us", "golden liberty", "equal to equal", 'B'},
    {"Who is widely credited with inventing the lightbulb?", "Thomas Edison", "Joseph Swan", "Nikola Tesla", "George Westinghouse", 'A'},
    {"The author of 'Zemsta' (The Revenge) is:", "Adam Mickiewicz", "Aleksander Fredro", "Juliusz Slowacki", "Henryk Sienkiewicz", 'B'},
    {"What is the capital of France?", "Berlin", "Madrid", "Paris", "Rome", 'C'},
    {"Which chemical element has the symbol O?", "Gold", "Oxygen", "Silver", "Hydrogen", 'B'},
    {"In what year did the Battle of Grunwald take place?", "1939", "1492", "1410", "1683", 'C'},
    {"The longest river in Poland is:", "Oder", "Warta", "Bug", "Vistula", 'D'},
    {"Microsoft was founded by:", "Steve Jobs", "Bill Gates", "Elon Musk", "Mark Zuckerberg", 'B'},
    {"How many legs does a healthy spider have?", "4", "6", "8", "10", 'C'},
    {"The chemical formula for water is:", "H2O", "CO2", "NaCl", "O2", 'A'},
    {"What is the name of Earth's natural satellite?", "Mars", "Moon", "Sun", "Venus", 'B'},
    {"The capital of Australia is:", "Sydney", "Melbourne", "Perth", "Canberra", 'D'},
    {"The main ingredient in sushi is:", "Rice", "Pasta", "Potatoes", "Bread", 'A'},
    {"Frederic Chopin was a famous:", "Painter", "Poet", "Composer", "General", 'C'},
    {"The famous 'Maluch' is a car of the brand:", "Polonez", "Fiat 126p", "Syrena", "Warszawa", 'B'},
    {"What color is at the top of the Polish flag?", "White", "Red", "Blue", "Yellow", 'A'},
    {"Billy goats are the symbol of which city?", "Krakow", "Gdansk", "Wroclaw", "Poznan", 'D'},
    {"The king of the animals is the:", "Lion", "Elephant", "Tiger", "Giraffe", 'A'},
    {"Who stopped the Sun and moved the Earth?", "Johannes Hevelius", "Nicolaus Copernicus", "Galileo", "Isaac Newton", 'B'},
    {"At what temperature does water boil (at normal pressure)?", "90 C", "110 C", "100 C", "0 C", 'C'},
    {"The ship that sank in 1912 after hitting an iceberg is:", "Britannic", "Titanic", "Olympic", "Carpathia", 'B'},
    {"Which country is shaped like a boot?", "Spain", "Italy", "Greece", "Portugal", 'B'},
    {"What is the chemical symbol for gold?", "Ag", "Au", "Fe", "Cu", 'B'},
    {"How many items are in a dozen?", "10", "12", "15", "20", 'B'},
    {"Who wrote the tragedy 'Romeo and Juliet'?", "Moliere", "Goethe", "Shakespeare", "Mickiewicz", 'C'},
    {"What is the name of the largest ocean on Earth?", "Atlantic", "Indian", "Arctic", "Pacific", 'D'},
    {"In what year did World War II begin?", "1914", "1939", "1945", "1920", 'B'},
    {"Which instrument has a keyboard?", "Guitar", "Violin", "Piano", "Trumpet", 'C'},
    {"What is the currency of the United Kingdom?", "Euro", "Dollar", "Pound sterling", "Franc", 'C'},
    {"Which continent is the largest by land area?", "Africa", "North America", "Asia", "Europe", 'C'},
    {"Who was the first king of Poland?", "Casimir the Great", "Mieszko I", "Boleslaw the Brave", "Wladyslaw Jagiello", 'C'},
    {"What is the name of the famous detective from Arthur Conan Doyle's novels?", "Poirot", "Holmes", "Columbo", "Bond", 'B'},
    {"Which country does pizza come from?", "France", "Italy", "Spain", "Turkey", 'B'},
    {"What is the approximate value of Pi?", "3.14", "2.15", "4.50", "3.00", 'A'},
    {"Which gas is essential for humans to breathe?", "Hydrogen", "Nitrogen", "Oxygen", "Helium", 'C'},
    {"The capital of the United States is:", "New York", "Los Angeles", "Washington", "Chicago", 'C'},
    {"Who is the author of the theory of relativity?", "Isaac Newton", "Albert Einstein", "Nikola Tesla", "Marie Sklodowska-Curie", 'B'},
    {"What is the name of the longest river in the world?", "Nile", "Amazon", "Vistula", "Mississippi", 'A'},
    {"How many years are in a century?", "10", "50", "100", "1000", 'C'},
    {"Which planet is called the Red Planet?", "Venus", "Mars", "Jupiter", "Saturn", 'B'},
    {"What is the main ingredient of guacamole?", "Tomato", "Avocado", "Onion", "Pepper", 'B'},
    {"In which sport is a puck used?", "Football", "Tennis", "Ice Hockey", "Rugby", 'C'},
    {"Which of the following is NOT a color of the French flag?", "Blue", "White", "Red", "Yellow", 'D'},
    {"What is a female horse called?", "Mare", "Stallion", "Foal", "Gelding", 'A'},
    {"In which city is the Colosseum located?", "Paris", "Rome", "Athens", "London", 'B'},
    {"How many hearts does an octopus have?", "One", "Two", "Three", "It has no heart", 'C'},
    {"Who patented the telephone?", "Alexander Bell", "Nikola Tesla", "Thomas Edison", "Guglielmo Marconi", 'A'},
    {"What does a thermometer measure?", "Pressure", "Humidity", "Temperature", "Wind", 'C'},
    {"What is the process of turning water into ice called?", "Evaporation", "Freezing", "Melting", "Condensation", 'B'},
    {"Which element is the main component of a diamond?", "Carbon", "Gold", "Silicon", "Sulfur", 'A'},
    {"How many players are on a football team on the pitch?", "9", "10", "11", "12", 'C'},
    {"How many days are in a week?", "5", "6", "7", "8", 'C'},
    {"What color is made by mixing yellow and blue?", "Red", "Green", "Purple", "Black", 'B'},
    {"What do we drink from a cow's udder?", "Juice", "Water", "Milk", "Cola", 'C'},
    {"Where does Donald Duck live?", "Duckburg", "Gotham", "Hogwarts", "Middle-earth", 'A'},
    {"What fruit is the symbol of Apple?", "Pear", "Apple", "Banana", "Cherry", 'B'},
    {"How much is 2 times 2?", "2", "4", "6", "8", 'B'},
    {"How do fish breathe?", "With lungs", "With gills", "Through skin", "With noses", 'B'},
    {"Which animal barks?", "Cat", "Dog", "Cow", "Pig", 'B'},
    {"What do you wear on your hands in winter?", "Socks", "Hat", "Gloves", "Scarf", 'C'},
    {"Which season comes after winter?", "Summer", "Autumn", "Spring", "Winter", 'C'},
    {"In which sport is a racket used?", "Football", "Volleyball", "Tennis", "Basketball", 'C'},
    {"Who was Michael Jackson?", "A singer", "A painter", "A president", "An athlete", 'A'},
    {"What does a baker do?", "Heals people", "Bakes bread", "Repairs shoes", "Puts out fires", 'B'},
    {"What color is grass?", "Blue", "Red", "Green", "Yellow", 'C'},
    {"Where is Poland located?", "In Asia", "In Africa", "In Europe", "In America", 'C'},
    {"How many fingers does a human have on one hand?", "4", "5", "6", "10", 'B'},
    {"Which animal has a long neck?", "Elephant", "Giraffe", "Lion", "Hippopotamus", 'B'},
    {"What do you brush your teeth with?", "Toothbrush", "Spoon", "Fork", "Sponge", 'A'},
    {"What falls from clouds?", "Sand", "Stones", "Rain", "Leaves", 'C'},
    {"What is the result of adding 50 + 50?", "50", "100", "150", "200", 'B'},
    {"What is the name of the fairy tale character who loses a glass slipper?", "Snow White", "Cinderella", "Rapunzel", "Ariel", 'B'},
    {"What does a hen lay?", "Gold", "Eggs", "Stones", "Milk", 'B'},
    {"What color is a fire engine?", "Blue", "Yellow", "Red", "White", 'C'},
    {"Where do we buy medicines?", "In a pharmacy", "In a bakery", "At the cinema", "At the post office", 'A'},
    {"How many wheels does a passenger car have?", "2", "3", "4", "6", 'C'},
    {"What is a young dog called?", "Kitten", "Puppy", "Foal", "Calf", 'B'},
    {"What is the source of light during the day?", "Moon", "Stars", "Sun", "Lantern", 'C'},
    {"Which animal gives wool?", "Cow", "Sheep", "Goat", "Pig", 'B'},
    {"In which game is a gamepad used?", "In a board game", "In a video game", "In football", "In hide and seek", 'B'},
    {"What grows in a forest?", "Mushrooms", "Cars", "Houses", "Televisions", 'A'},
    {"Which object is used for writing?", "Hammer", "Pen", "Fork", "Comb", 'B'},
    {"What is the capital of Germany?", "Munich", "Berlin", "Hamburg", "Bonn", 'B'},
    {"How many minutes are in an hour?", "30", "45", "60", "100", 'C'},
    {"Which gas inflates balloons to make them fly?", "Oxygen", "Helium", "Nitrogen", "Hydrogen", 'B'},
    {"Which animal has a trunk?", "Rhinoceros", "Elephant", "Hippopotamus", "Tiger", 'B'},
    {"Who is Batman?", "Spider-Man", "Bat-Man", "Iron-Man", "Ant-Man", 'B'},
    {"What do you kick the ball into in football?", "Into a basket", "Into a goal", "Over a net", "Into a hole", 'B'},
    {"Which instrument has strings?", "Drum", "Flute", "Guitar", "Trumpet", 'C'},
    {"What is needed to make scrambled eggs?", "Flour", "Eggs", "Sugar", "Water", 'B'},
    {"Which animal is a symbol of wisdom?", "Owl", "Hen", "Goose", "Crow", 'A'},
    {"What do the stripes on the road mean?", "Pedestrian crossing", "Parking", "Bus stop", "Race start", 'A'},
    {"What color is coal?", "White", "Gray", "Black", "Brown", 'C'},
    {"Who delivers letters?", "Plumber", "Postman", "Driver", "Police officer", 'B'},
    {"What do we eat soup with?", "A fork", "A knife", "A spoon", "Our hands", 'C'},
    {"What is the center of an egg called?", "Egg white", "Yolk", "Shell", "Embryo", 'B'},
    {"What does a clock do?", "Sings", "Measures time", "Cooks", "Shines", 'B'},
    {"Which month is the first in the year?", "February", "January", "March", "December", 'B'},
    {"Which animal has stripes?", "Zebra", "Horse", "Donkey", "Camel", 'A'},
    {"What floats on the sea?", "Airplane", "Train", "Ship", "Bus", 'C'},
    {"What shape is a ball?", "Square", "Triangular", "Round (sphere)", "Rectangular", 'C'},
    {"Where do we watch movies on a big screen?", "In a theater", "In a cinema", "At school", "In a shop", 'B'}
};

const Question medium[] =
{
    {"What is the capital of Canada?", "Toronto", "Vancouver", "Ottawa", "Montreal", 'C'},
    {"Who discovered penicillin?", "Louis Pasteur", "Alexander Fleming", "Marie Curie", "Robert Koch", 'B'},
    {"Approximately how many bones are in an adult human body?", "206", "150", "300", "500", 'A'},
    {"Which Roman god is the equivalent of the Greek Zeus?", "Apollo", "Mars", "Jupiter", "Neptun", 'C'},
    {"What is the currency of Japan?", "Won", "Yuan", "Yen", "Ringgit", 'C'},
    {"At what address in London did Sherlock Holmes live?", "10 Downing Street", "221B Baker Street", "5 Oxford Street", "12 Abbey Road", 'B'},
    {"Who was the first human in space?", "Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "John Glenn", 'B'},
    {"What does the Roman numeral C represent?", "50", "100", "500", "1000", 'B'},
    {"What is the name of the author of 'The Lord of the Rings' saga?", "J.K. Rowling", "George R.R. Martin", "J.R.R. Tolkien", "C.S. Lewis", 'C'},
    {"Which mineral is the hardest on the Mohs scale?", "Quartz", "Topaz", "Diamond", "Corundum", 'C'},
    {"In which year did a human first step on the Moon?", "1959", "1969", "1975", "1980", 'B'},
    {"What is the name of the smallest country in the world?", "Monaco", "San Marino", "Vatican City", "Liechtenstein", 'C'},
    {"Which country do LEGO bricks come from?", "Germany", "Sweden", "Denmark", "USA", 'C'},
    {"Which of these elements is a noble metal?", "Iron", "Zinc", "Platinum", "Copper", 'C'},
    {"Who painted 'Sunflowers'?", "Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Salvador Dali", 'B'},
    {"What is the holy book of Islam called?", "Torah", "Bible", "Quran", "Vedas", 'C'},
    {"How many stars are on the flag of the European Union?", "10", "12", "15", "27", 'B'},
    {"Which part of the body produces insulin?", "Liver", "Pancreas", "Kidneys", "Heart", 'B'},
    {"What is measured in hertz (Hz)?", "Voltage", "Power", "Frequency", "Sound", 'C'},
    {"What is the name of the mythical land ruled by King Arthur?", "Narnia", "Middle-earth", "Camelot", "Avalon", 'C'},
    {"Which ocean washes the shores of Poland?", "None (a sea does)", "Atlantic", "Pacific", "Indian", 'A'},
    {"What is a male bee called?", "Drone", "Queen", "Worker", "Bumblebee", 'A'},
    {"Where were the first modern Olympic Games held (1896)?", "In Paris", "In London", "In Athens", "In Rome", 'C'},
    {"What is the name of the main character in 'Crime and Punishment'?", "Raskolnikov", "Karamazov", "Karenin", "Onegin", 'A'},
    {"How many squares are on a chessboard?", "50", "64", "100", "32", 'B'},
    {"Which city does the band The Beatles come from?", "London", "Manchester", "Liverpool", "Bristol", 'C'},
    {"Which gas dominates the Earth's atmosphere?", "Oxygen", "Nitrogen", "Carbon dioxide", "Argon", 'B'},
    {"What is the name of the deepest place on Earth?", "Mariana Trench", "Japan Trench", "Atacama Trench", "Challenger Deep", 'A'},
    {"Which country won the FIFA World Cup in 2014?", "Brazil", "Argentina", "Germany", "Spain", 'C'},
    {"What does the abbreviation WWW stand for?", "World Wide Web", "World Wide Wifi", "Web World Wide", "Wild Wild West", 'A'},
    {"In what year did Poland regain independence?", "1914", "1918", "1920", "1939", 'B'},
    {"What is the currency of Russia?", "Dollar", "Euro", "Ruble", "Pound", 'C'},
    {"Who invented the printing press?", "Copernicus", "Gutenberg", "Edison", "Tesla", 'B'},
    {"What is a male cow called?", "Bull", "Stallion", "Ram", "Boar", 'A'},
    {"How many zeros are in a million?", "5", "6", "9", "12", 'B'},
    {"Which planet is closest to the Sun?", "Venus", "Mars", "Mercury", "Earth", 'C'},
    {"On which continent is Egypt located?", "In Asia", "In Europe", "In Africa", "In America", 'C'},
    {"What does the abbreviation PC stand for?", "Personal Computer", "Private Center", "Police Car", "Power Cable", 'A'},
    {"Who is the author of 'The Doll' (Lalka)?", "Henryk Sienkiewicz", "Boleslaw Prus", "Stefan Zeromski", "Adam Mickiewicz", 'B'},
    {"What is the capital of Spain?", "Barcelona", "Madrid", "Seville", "Valencia", 'B'},
    {"What are french fries made of?", "Rice", "Flour", "Potatoes", "Corn", 'C'},
    {"How many years is the term of the President of Poland?", "4", "5", "6", "7", 'B'},
    {"Which city was the capital of Poland before Warsaw?", "Gniezno", "Poznan", "Krakow", "Wroclaw", 'C'},
    {"Which element has the symbol Na?", "Nitrogen", "Sodium", "Potassium", "Nickel", 'B'},
    {"What is the name of the largest animal in the world?", "African elephant", "Blue whale", "Whale shark", "Giraffe", 'B'},
    {"Who painted the 'Mona Lisa'?", "Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello", 'B'},
    {"In which city does the Eiffel Tower stand?", "In London", "In Berlin", "In Paris", "In Rome", 'C'},
    {"What is the name of the Polish female Nobel Prize laureate in poetry?", "Olga Tokarczuk", "Wislawa Szymborska", "Maria Konopnicka", "Eliza Orzeszkowa", 'B'},
    {"How many degrees are in a right angle?", "45 degrees", "60 degrees", "90 degrees", "180 degrees", 'C'},
    {"Which country does IKEA come from?", "Norway", "Denmark", "Sweden", "Finland", 'C'},
    {"What is the fastest land animal?", "Lion", "Hare", "Cheetah", "Gazelle", 'C'},
    {"Which organ in humans pumps blood?", "Lungs", "Liver", "Stomach", "Heart", 'D'},
    {"What is the name of the famous Polish ski jumper from Wisla?", "Kamil Stoch", "Piotr Zyla", "Adam Malysz", "Dawid Kubacki", 'C'},
    {"What is hockey?", "A card game", "A team game on ice", "A type of dance", "A martial art", 'B'},
    {"In which year did Poland join the European Union?", "2000", "2004", "2010", "1999", 'B'},
    {"What is the main ingredient of glass?", "Sand (silica)", "Clay", "Limestone", "Coal", 'A'},
    {"How much is a dozen?", "12", "13", "20", "6", 'A'},
    {"Which river flows through London?", "Seine", "Thames", "Rhine", "Danube", 'B'},
    {"What is the name of the god of war in Roman mythology?", "Zeus", "Ares", "Mars", "Jupiter", 'C'},
    {"What is the capital of Italy?", "Milan", "Naples", "Rome", "Turin", 'C'},
    {"What is the chemical symbol for iron?", "Ze", "Fe", "Ir", "Zn", 'B'},
    {"Who wrote 'Pan Tadeusz'?", "Juliusz Slowacki", "Cyprian Kamil Norwid", "Adam Mickiewicz", "Jan Kochanowski", 'C'},
    {"How many players are on a volleyball team on the court?", "5", "6", "7", "11", 'B'},
    {"What is the name of the largest land mammal?", "African elephant", "White rhinoceros", "Hippopotamus", "Bison", 'A'},
    {"In which country is Machu Picchu located?", "In Mexico", "In Peru", "In Brazil", "In Chile", 'B'},
    {"Who invented the light bulb?", "Edison", "Tesla", "Bell", "Marconi", 'A'},
    {"Which country has a flag with a maple leaf?", "USA", "Canada", "Japan", "Brazil", 'B'},
    {"What does GDP (PKB) stand for in Polish?", "Polish Business Club", "Gross Domestic Product", "Universal Savings Bank", "Polish Budget Commission", 'B'},
    {"What is the highest peak in the Tatra Mountains?", "Giewont", "Rysy", "Kasprowy Wierch", "Gerlach", 'D'},
    {"Who was the first president of the Third Polish Republic elected by popular vote?", "Wojciech Jaruzelski", "Lech Walesa", "Aleksander Kwasniewski", "Lech Kaczynski", 'B'},
    {"What is the study of animals called?", "Botany", "Zoology", "Geology", "Astronomy", 'B'},
    {"Which continent is the coldest?", "Antarctica", "Arctic", "Asia", "Europe", 'A'},
    {"How many strings does a typical classical guitar have?", "4", "5", "6", "12", 'C'},
    {"Who directed 'Schindler's List'?", "Roman Polanski", "Steven Spielberg", "Andrzej Wajda", "Quentin Tarantino", 'B'},
    {"What is photosynthesis?", "Taking photos", "Plant nutrition process", "3D printing", "Skin disease", 'B'},
    {"What is the capital of the Czech Republic?", "Bratislava", "Prague", "Vienna", "Budapest", 'B'},
    {"Who is the patron saint of drivers?", "Saint Christopher", "Saint Peter", "Saint Paul", "Saint Nicholas", 'A'},
    {"How many sides does a hexagon have?", "5", "6", "7", "8", 'B'},
    {"In which city was Nicolaus Copernicus born?", "In Warsaw", "In Krakow", "In Torun", "In Gdansk", 'C'},
    {"Which river is the longest in Europe?", "Danube", "Volga", "Rhine", "Vistula", 'B'},
    {"Who played the lead role in the movie 'Titanic'?", "Brad Pitt", "Tom Cruise", "Leonardo DiCaprio", "Johnny Depp", 'C'},
    {"What is the name of the Polish national anthem?", "Rota", "Mazurek Dabrowskiego", "Bogurodzica", "Warszawianka", 'B'},
    {"What is origami?", "Martial art", "Art of paper folding", "Japanese dish", "Type of sword", 'B'},
    {"Who was the commander of the Kosciuszko Uprising?", "Tadeusz Kosciuszko", "Jozef Pilsudski", "Jozef Poniatowski", "Jan Henryk Dabrowski", 'A'},
    {"Which city is famous for its gingerbread?", "Poznan", "Torun", "Wroclaw", "Lublin", 'B'},
    {"Which country does pizza come from?", "Spain", "Greece", "Italy", "France", 'C'},
    {"How long does a football match last (regular time)?", "60 minutes", "80 minutes", "90 minutes", "100 minutes", 'C'},
    {"What is the capital of Ukraine?", "Lviv", "Kyiv", "Kharkiv", "Odessa", 'B'},
    {"Which metal is liquid at room temperature?", "Gold", "Lead", "Mercury", "Silver", 'C'},
    {"Who is the author of 'The Witcher'?", "Jacek Dukaj", "Stanislaw Lem", "Andrzej Sapkowski", "Szczepan Twardoch", 'C'},
    {"What is the name of the famous detective from Agatha Christie's novels?", "Sherlock Holmes", "Hercule Poirot", "Philip Marlowe", "Columbo", 'B'},
    {"In which year did World War I end?", "1914", "1918", "1920", "1939", 'B'},
    {"What is the deepest lake in Poland?", "Sniardwy", "Morskie Oko", "Hancza", "Wigry", 'C'},
    {"What is ZUS?", "Social Services Union", "Social Insurance Institution", "Sanitary Services Team", "United Car Insurances", 'B'},
    {"Who painted 'Lady with an Ermine'?", "Rembrandt", "Leonardo da Vinci", "Picasso", "Matejko", 'B'},
    {"Which country has the largest population (2023)?", "USA", "China", "India", "Russia", 'C'},
    {"From which kingdom does Simba come?", "From the jungle", "From the Pride Lands", "From Narnia", "From the Zoo", 'B'},
    {"What is the tallest building in Poland (up to the roof)?", "Palace of Culture", "Varso Tower", "Sky Tower", "Zlota 44", 'B'},
    {"Which element is C?", "Calcium", "Carbon", "Chlorine", "Tin", 'B'},
};

const Question hard[] =
{
    {"What is the chemical symbol for tungsten?", "Wo", "W", "Lf", "Tu", 'B'},
    {"In what year did the Berlin Wall fall?", "1987", "1989", "1991", "1993", 'B'},
    {"Who was the author of the 'Divine Comedy'?", "Petrarch", "Boccaccio", "Dante Alighieri", "Machiavelli", 'C'},
    {"What is the capital of Brazil?", "Rio de Janeiro", "Sao Paulo", "Brasilia", "Salvador", 'C'},
    {"How many keys does a standard piano have?", "66", "78", "88", "102", 'C'},
    {"Which Polish king died at Varna?", "Wladyslaw Jagiello", "Wladyslaw of Varna", "Casimir Jagiellon", "John I Albert", 'B'},
    {"What is the name of the largest island in the world?", "Madagascar", "Greenland", "Borneo", "New Guinea", 'B'},
    {"Who composed the opera 'The Magic Flute'?", "Ludwig van Beethoven", "Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Frederic Chopin", 'C'},
    {"Which vitamin is produced in the skin under the influence of the sun?", "Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K", 'C'},
    {"What is the study of seals called?", "Numismatics", "Heraldry", "Sigillography", "Philately", 'C'},
    {"How many cervical vertebrae does a giraffe have?", "7", "12", "50", "20", 'A'},
    {"In which city is the main UN headquarters located?", "In Geneva", "In Brussels", "In New York", "In Paris", 'C'},
    {"Who invented dynamite?", "Thomas Edison", "Alfred Nobel", "Alexander Bell", "Isaac Newton", 'B'},
    {"What is the brightest star in the night sky?", "Sirius", "Polaris", "Betelgeuse", "Vega", 'A'},
    {"Which of these countries is not located in Africa?", "Kenya", "Nigeria", "Guyana", "Egypt", 'C'},
    {"What are the processes of cell division called?", "Mitosis and Meiosis", "Synthesis and Osmosis", "Fusion and Fission", "Transcription and Translation", 'A'},
    {"Who wrote 'Madame Bovary'?", "Victor Hugo", "Gustave Flaubert", "Honore de Balzac", "Emile Zola", 'B'},
    {"What temperature on the Celsius scale is absolute zero?", "-100 C", "-273.15 C", "-500 C", "-300 C", 'B'},
    {"What was the name of the first woman to win a Nobel Prize?", "Marie Sklodowska-Curie", "Wislawa Szymborska", "Selma Lagerlof", "Mother Teresa", 'A'},
    {"What is the name of the Greek goddess of wisdom?", "Hera", "Aphrodite", "Athena", "Artemis", 'C'},
    {"The fear of long words is:", "Arachnophobia", "Claustrophobia", "Hippopotomonstrosesquippedaliophobia", "Xenophobia", 'C'},
    {"Which chemical element was discovered first on the Sun, and then on Earth?", "Hydrogen", "Helium", "Oxygen", "Lithium", 'B'},
    {"What is the full name of the cartoon dog 'Scooby Doo'?", "Scoobert Doo", "Scooby Dooby", "Scoubidou", "Robert Doo", 'A'},
    {"Which country in Europe is the oldest republic in the world?", "Switzerland", "San Marino", "France", "Greece", 'B'},
    {"What is the exact distance of a marathon?", "40 km", "42 km", "42 km 195 m", "42 km 500 m", 'C'},
    {"Who is considered the father of (theoretical) computer science?", "Bill Gates", "Alan Turing", "Steve Jobs", "Ada Lovelace", 'B'},
    {"What color is the 'black box' in an airplane?", "Black", "Red", "Orange", "Blue", 'C'},
    {"How many main layers does the Earth's atmosphere consist of?", "3", "5", "7", "10", 'B'},
    {"In which year did Poland join NATO?", "1997", "1999", "2004", "2002", 'B'},
    {"What was the name of the first full-length Disney animated film?", "Snow White and the Seven Dwarfs", "Pinocchio", "Bambi", "Mickey Mouse", 'A'},
    { "How many minutes did the shortest war in world history (England vs Zanzibar) last?", "38", "15", "69", "96", 'A' },
    { "What product was the first in history to be scanned with a barcode?", "A can of cola", "Chewing gum", "Milk", "Newspaper", 'B' },
    { "Which country has the most time zones?", "Russia", "China", "USA", "France", 'D' },
    { "What is the plastic or metal tip of a shoelace called?", "Aglet", "Ferrule", "Pin", "Tip", 'A' },
    { "How many paintings did Vincent van Gogh sell during his lifetime (confirmed)?", "One", "Zero", "Five hundred", "Two", 'A' },
     {"In which year did Jozef Pilsudski die?", "1926", "1930", "1935", "1939", 'C'},
     {"What is the capital of Australia?", "Sydney", "Melbourne", "Canberra", "Perth", 'C'},
     {"How many elements are in the periodic table (as of 2024)?", "108", "112", "118", "125", 'C'},
     {"Who was the first king of Israel?", "David", "Solomon", "Saul", "Moses", 'C'},
     {"In what year was the WWW (World Wide Web) invented?", "1980", "1989", "1995", "1999", 'B'},
     {"What is the fear of spiders called?", "Claustrophobia", "Agoraphobia", "Arachnophobia", "Cynophobia", 'C'},
     {"Which country does the brand Nokia come from?", "Sweden", "Finland", "Norway", "Denmark", 'B'},
     {"Which pope reigned the longest (after St. Peter)?", "John Paul II", "Pius IX", "Leo XIII", "Pius XII", 'B'},
     {"What is the currency of Switzerland?", "Euro", "Crown", "Franc", "Mark", 'C'},
     {"What is the speed of light in a vacuum (approximately)?", "300,000 km/s", "150,000 km/s", "1,000,000 km/s", "3,000 km/s", 'A'},
     {"Which Polish king founded the Krakow Academy?", "Boleslaw the Brave", "Casimir the Great", "Wladyslaw Jagiello", "Stefan Batory", 'B'},
     {"In what year did the Battle of Vienna take place?", "1410", "1525", "1683", "1791", 'C'},
     {"What is the name of the smallest bone in the human body?", "Incus (Anvil)", "Stapes (Stirrup)", "Malleus (Hammer)", "Patella", 'B'},
     {"Which planet has the most moons (2024)?", "Jupiter", "Saturn", "Uranus", "Neptune", 'B'},
     {"Who wrote 'Ferdydurke'?", "Stanislaw I. Witkiewicz", "Witold Gombrowicz", "Slawomir Mrozek", "Czeslaw Milosz", 'B'},
     {"How many countries make up the United Kingdom?", "3", "4", "5", "2", 'B'},
     {"What is the atomic number of gold?", "47", "50", "79", "82", 'C'},
     {"Who was the first president of the USA?", "Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams", 'C'},
     {"In which year did the Titanic sink?", "1905", "1912", "1918", "1923", 'B'},
     {"What is the capital of Iceland?", "Helsinki", "Oslo", "Reykjavik", "Nuuk", 'C'},
     {"Which element has the symbol Sn?", "Silver", "Sulfur", "Tin", "Antimony", 'C'},
     {"Who painted 'The Scream'?", "Gustav Klimt", "Edvard Munch", "Egon Schiele", "Claude Monet", 'B'},
     {"How many years did the Hundred Years' War last?", "100", "99", "116", "120", 'C'},
     {"What is the name of the longest river in Asia?", "Ganges", "Yangtze", "Mekong", "Huang He", 'B'},
     {"Who composed 'The Four Seasons'?", "Bach", "Mozart", "Vivaldi", "Beethoven", 'C'},
     {"In which city are the Spanish Steps located?", "In Madrid", "In Barcelona", "In Rome", "In Seville", 'C'},
     {"What is a female moose called?", "Cow", "Doe", "She-wolf", "Sow", 'A'},
     {"Which of the Greek gods was the ruler of the underworld?", "Zeus", "Poseidon", "Hades", "Ares", 'C'},
     {"Which element are graphite and diamond made of?", "Silicon", "Carbon", "Titanium", "Iron", 'B'},
     {"What is Avogadro's number (approximately)?", "6.02 x 10^23", "3.14 x 10^5", "9.81 x 10^2", "1.6 x 10^-19", 'A'},
     {"What is the capital of New Zealand?", "Auckland", "Wellington", "Christchurch", "Sydney", 'B'},
     {"Who received the Nobel Prize twice in different fields?", "Albert Einstein", "Marie Sklodowska-Curie", "Linus Pauling", "Ernest Hemingway", 'B'},
     {"What is the name of the largest lake in the world?", "Lake Victoria", "Lake Superior", "Caspian Sea", "Lake Baikal", 'C'},
     {"In which year was the Constitution of May 3 adopted?", "1772", "1791", "1795", "1830", 'B'},
     {"Who is the creator of the painting 'The Creation of Adam'?", "Leonardo da Vinci", "Michelangelo", "Donatello", "Botticelli", 'B'},
     {"Which country in South America is landlocked?", "Brazil", "Chile", "Bolivia", "Venezuela", 'C'},
     {"Which vitamin is called ascorbic acid?", "A", "B12", "C", "D", 'C'},
     {"What is the sum of the angles in a triangle?", "90", "180", "360", "270", 'B'},
     {"Who wrote '1984'?", "Aldous Huxley", "George Orwell", "Ray Bradbury", "Franz Kafka", 'B'},
     {"What is the currency of Croatia (since 2023)?", "Kuna", "Euro", "Dinar", "Lira", 'B'},
     {"Where is the Gobi Desert located?", "In Africa", "In North America", "In Asia", "In Australia", 'C'},
     {"Which Polish king was called 'the Saxon'?", "Augustus II", "Stanislaw Augustus", "John III", "Sigismund III", 'A'},
     {"What is the heaviest natural element?", "Radium", "Lead", "Uranium", "Plutonium", 'C'},
     {"What is the name of the oldest university in Poland?", "University of Warsaw", "Jagiellonian University", "University of Wroclaw", "KUL", 'B'},
     {"In what year was YouTube founded?", "2000", "2005", "2008", "2010", 'B'},
     {"Who was the lead singer of the band Queen?", "Mick Jagger", "David Bowie", "Freddie Mercury", "Elton John", 'C'},
     {"What is the highest peak in Africa?", "Mont Blanc", "Elbrus", "Kilimanjaro", "Aconcagua", 'C'},
     {"How many voivodeships are there in Poland?", "14", "15", "16", "17", 'C'},
     {"Which country produces the most coffee in the world?", "Colombia", "Vietnam", "Brazil", "Ethiopia", 'C'},
     {"What is the study of maps called?", "Geodesy", "Cartography", "Topography", "Geography", 'B'},
     {"Who invented (improved) the steam engine?", "James Watt", "Thomas Newcomen", "George Stephenson", "Robert Fulton", 'A'},
     {"What is a 'black hole'?", "A planet", "An area of massive gravity", "A type of star", "A hole in the ozone", 'B'},
     {"What color is octopus blood?", "Red", "Blue", "Green", "Black", 'B'},
     {"In which year did a human first orbit the Earth (Gagarin)?", "1957", "1961", "1969", "1972", 'B'},
     {"What is the capital of Turkey?", "Istanbul", "Antalya", "Ankara", "Izmir", 'C'},
     {"Who was the first prime minister of the Third Polish Republic?", "Jacek Kuron", "Tadeusz Mazowiecki", "Jan Olszewski", "Leszek Balcerowicz", 'B'},
     {"Which element has the symbol K?", "Krypton", "Potassium", "Calcium", "Cobalt", 'B'},
     {"What is the name of the largest island in the Mediterranean Sea?", "Sardinia", "Corsica", "Sicily", "Cyprus", 'C'},
     {"Who wrote 'Quo Vadis'?", "Boleslaw Prus", "Stefan Zeromski", "Henryk Sienkiewicz", "Wladyslaw Reymont", 'C'},
     {"How many teeth does an adult human have (full set)?", "28", "30", "32", "34", 'C'},
     {"What is the name of the current King of Great Britain (2024)?", "Charles III", "William V", "George VII", "Edward IX", 'A'},
     {"Where was Frederic Chopin born?", "In Warsaw", "In Zelazowa Wola", "In Paris", "In Krakow", 'B'},
     {"What is Bitcoin?", "A company", "A cryptocurrency", "A bank", "An operating system", 'B'},
     {"In what year did the USSR collapse?", "1989", "1990", "1991", "1993", 'C'},
     {"What is the name of the god of thunder in Norse mythology?", "Odin", "Thor", "Loki", "Freyja", 'B'}
};

const int NUM_EASY = sizeof( easy ) / sizeof( easy[ 0 ] );
const int NUM_MEDIUM = sizeof( medium ) / sizeof( medium[ 0 ] );
const int NUM_HARD = sizeof( hard ) / sizeof( hard[ 0 ] );

const int rewards[ 13 ] =
{
    0,
    500,
    1000,
    2000,
    5000,
    10000,
    20000,
    40000,
    75000,
    125000,
    250000,
    500000,
    1000000
};